### ISSUE TITLE
owners of erlzmq

### ISSUE THREAD

**Issue by saleyn** [zeromq/erlzmq#26]
For some reason I no longer can see the settings of this project.  Likely because lost owner status for some reason.  Is anybody else on the owners list here?  If so, please re-add me back in.

**Comment by yrashk** [comment]
It's weird. I can go to https://github.com/zeromq/erlzmq/settings/collaboration to see the teams, but when I click on `erlzmq administrators` team, it leads me to https://github.com/orgs/zeromq/teams/erlzmq-administrators which renders 404.

**Comment by yrashk** [comment]
I was able to create a new team for erlzmq admins, but I can't invite anybody to it (only organization owners can). cc @c-rack @sappo @somdoron

**Comment by saleyn** [comment]
@c-rack @sappo @somdoron: Please re-invite me to this team if you can.

**Comment by bluca** [comment]
Done.
Please enable 2-factor authentication on Github if you haven't already!

**Comment by saleyn** [comment]
Thanks.
